### ISSUE TITLE
change in institutionCode values

### ISSUE THREAD

**Issue by JoyceGross** [junyinglim/TranscriptResolver#1]
We changed CIS to UCIS in the bnhm_id field -- yes, not good, we changed the (semi) unique identifiers.

I think there will need to be a hack added somewhere (in transcriptPrepare.py and maybe elsewhere) so that bnhm_ids that start with CIS are changed to UCIS.

Meanwhile, I easily changed those values in the load file once I put it in Excel.

But when records were checked to see if they had been databased, they would not have been found even if they had been databased.....

**Comment by junyinglim** [comment]
It's annoying since the mistake is being propagated by the images themselves. I will add a line at the end of transcriptClean that basically just substitutes CIS for UCIS.

**Comment by JoyceGross** [comment]
Yes I agree this is annoying. In the future, I'm going to try to discourage anyone from having me change institutionCodes. It causes a cascading series of work all the way down the pipeline ... and along several pipelines.

**Comment by junyinglim** [comment]
besides UCIS, you mentioned there were more? probably an easy fix

**Comment by JoyceGross** [comment]
No, I think UCIS was the only change in the bnhm_id field. I hope!
I just have to track down a last holdingInstitution value (different issue). Sent Pete an email last night. Am going to track him down in person shortly.
