### ISSUE TITLE
non-California counties in California

### ISSUE THREAD

**Issue by JoyceGross** [junyinglim/TranscriptResolver#4]
According to my memory the TranscriptResolver is checking for valid California counties, right? The bulk loader found some invalid ones:

Error .... Specimens Worksheet, Row 1095: State is California but <b>Hidalgo County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 3744: State is California but <b>Wabasha County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 4860: State is California but <b>Douglas County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 6490: State is California but <b>Wabasha County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 7621: State is California but <b>Clay County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 8193: State is California but <b>Navajo County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 9416: State is California but <b>Utah County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 17636: State is California but <b>Bonner County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 20264: State is California but <b>Monroe County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 22108: State is California but <b>New York County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 24671: State is California but <b>El Paso County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 24709: State is California but <b>Pima County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 25580: State is California but <b>Rio Arriba County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 26183: State is California but <b>Washoe County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 26971: State is California but <b>Ransom County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 27170: State is California but <b>Ransom County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 27707: State is California but <b>Pierce County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 29818: State is California but <b>Pima County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 32934: State is California but <b>Chaves County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 33408: State is California but <b>Davis County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 33919: State is California but <b>Eddy County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 35082: State is California but <b>Philadelphia County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 36460: State is California but <b>Hidalgo County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 37412: State is California but <b>Ransom County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 37985: State is California but <b>Lyon County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 38735: State is California but <b>Liberty County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 39860: State is California but <b>Maui County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 40287: State is California but <b>Richland County</b> is not an approved California county.<br>
Error .... Specimens Worksheet, Row 40578: State is California but <b>Hidalgo County</b> is not an approved California county.<br>

**Comment by junyinglim** [comment]
Examining these cases, it appears that this is not due to the code per se, but the fact that the bnhmids or NFN ids are not unique (multiple images to the same ID) and so was scrambled during the resolving process. I think it's a better idea that you dealt with these records manually and individually, because they probably suggest something really bad screwed up in the file naming process or on the NFN end.
