### ISSUE TITLE
holdingInstitution changes

### ISSUE THREAD

**Issue by JoyceGross** [junyinglim/TranscriptResolver#5]
We'll have to change 3 or 4 of the holdingInstitution values in essig_inst.csv.
Will post details when I have everything straight.

**Comment by junyinglim** [comment]
Lemme know once you're ready

**Comment by JoyceGross** [comment]
ok, these are the ones that need changing:

UMMZI -> University of Michigan Museum of Zoology
UCRCENT->University of California Riverside, Entomology Research Museum
LACM->Los Angeles County Museum
SBMNHENT->Santa Barbara Museum of Natural History

Unfortunately, I see one more problem I'm not sure what to do about with the "CIS" or "UCIS" records. 

PETE: The TranscriptResolver code currently maps

CIS->University of California, Riverside (UCR), Entomology Research Museum

I've asked Jun to change CIS to UCIS. So it should be:

UCIS->University of California Riverside, Entomology Research Museum

HOWEVER, the Essig database has UCIS specimens listed at both Essig and Riverside. 

mysql> select count(_), holdinginstitution from eme where bnhm_id like 'ucis%' group by holdinginstitution order by holdinginstitution;
+----------+----------------------------+
| count(_) | holdinginstitution         |
+----------+----------------------------+
|      415 | University of California Riverside, Entomology Research Museum |
|      299 | Essig Museum of Entomology |
+----------+----------------------------+
2 rows in set (0.10 sec)

Which way do we map UCIS in the TranscriptResolver?? We can only have one mapping per institutionCode.

**Comment by poboyski** [comment]
UCIS is a collection code (which we call Institution Code in the EssigDB). Specimens with these numbers exist in several collections, mostly Essig and Riverside. However, anything coming back from Notes From Nature would be Essig specimens, since Riverside does not image specimens. Therefore all UCIS specimens should map to Essig Museum of Entomology.

**Comment by junyinglim** [comment]
Created a new institution mapping. Let me know if that doesn't rectify the issues
